### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by misha-plus** [misha-plus/power-start#2]
- [X] Integrate frontend part into the server
- [x] Add building frontend part on Travis
- [x] Auto release
- [x] Add a screenshot
- [x] Add logo to readme
- [x] Fix built-in web interface
